version: 1.0.{build}
image:
- Visual Studio 2017
platform:
  - x64
configuration:
  - Release
  - Debug
install:
    - git submodule update --init --recursive
    - set QTDIR=C:\Qt\5.11\msvc2017_64
    - set BOOST_ROOT=C:\Libraries\boost_1_67_0
    - set PATH=%PATH%;%QTDIR%\bin
before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" ..
    - dir
build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln
